// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDObhqr3nzwhCXA-ZIb_T1TubC9bLeydng',
    appId: '1:405116789511:web:123ec5563f47da92bf1ba2',
    messagingSenderId: '405116789511',
    projectId: 'flutter-cli-831',
    authDomain: 'flutter-cli-831.firebaseapp.com',
    storageBucket: 'flutter-cli-831.appspot.com',
    measurementId: 'G-6LL976JY0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCKwUYCSpAI5I5DzXXmbJJyxTPXVH6bE',
    appId: '1:405116789511:android:b687d21c02f7e3acbf1ba2',
    messagingSenderId: '405116789511',
    projectId: 'flutter-cli-831',
    storageBucket: 'flutter-cli-831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_JnOkXTFFUAxshWOAecwv_rY9OE7EEE',
    appId: '1:405116789511:ios:9271002c2e56912abf1ba2',
    messagingSenderId: '405116789511',
    projectId: 'flutter-cli-831',
    storageBucket: 'flutter-cli-831.appspot.com',
    iosClientId: '405116789511-vuqm52o9aa75n02766uq4ai0tskfntu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_JnOkXTFFUAxshWOAecwv_rY9OE7EEE',
    appId: '1:405116789511:ios:38068f89536517d5bf1ba2',
    messagingSenderId: '405116789511',
    projectId: 'flutter-cli-831',
    storageBucket: 'flutter-cli-831.appspot.com',
    iosClientId: '405116789511-lm4pf5ju4iq23e4kjdpr6h2k5dhvi9vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCli.RunnerTests',
  );
}
