// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZH9OAgtFqhQt1fOetFxa9VAFY5tE174',
    appId: '1:71327912960:web:2f7a8ba1848c6c8401f4e5',
    messagingSenderId: '71327912960',
    projectId: 'fb-push-notifications-aa7b6',
    authDomain: 'fb-push-notifications-aa7b6.firebaseapp.com',
    storageBucket: 'fb-push-notifications-aa7b6.appspot.com',
    measurementId: 'G-JNZYY804JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxempdRoZN1cq0yb8GvKyxca01hCzcRUs',
    appId: '1:71327912960:android:46f6af42e109951901f4e5',
    messagingSenderId: '71327912960',
    projectId: 'fb-push-notifications-aa7b6',
    storageBucket: 'fb-push-notifications-aa7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefvPLB7el4oSh9Z7903QXqQDv6tnVu6k',
    appId: '1:71327912960:ios:404f4e0b7596333601f4e5',
    messagingSenderId: '71327912960',
    projectId: 'fb-push-notifications-aa7b6',
    storageBucket: 'fb-push-notifications-aa7b6.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );
}
