// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA26q9n8cTZ-DWLdp8Us5oFw-wtbclatjc',
    appId: '1:740789149324:web:1f0714c01b3fe3ee6da5a9',
    messagingSenderId: '740789149324',
    projectId: 'fb-storage-aece9',
    authDomain: 'fb-storage-aece9.firebaseapp.com',
    storageBucket: 'fb-storage-aece9.appspot.com',
    measurementId: 'G-YMS9TY5H9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChpTR7COMbT6kKdfE9PAPqPQKQd8mRbX0',
    appId: '1:740789149324:android:410a556c320eebbf6da5a9',
    messagingSenderId: '740789149324',
    projectId: 'fb-storage-aece9',
    storageBucket: 'fb-storage-aece9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCvM6qMpoYu1ciVjpetbKPXs_5JxvQX4',
    appId: '1:740789149324:ios:1d8fe19c47b38cae6da5a9',
    messagingSenderId: '740789149324',
    projectId: 'fb-storage-aece9',
    storageBucket: 'fb-storage-aece9.appspot.com',
    iosBundleId: 'com.example.fbStorage',
  );
}
